const ActionTypes = {
    COLLAPS_MENU: 'COLLAPS_MENU',

    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE:'FETCH_DATA_FAILURE'
}

export default ActionTypes;
