const ActionTypes = {
    COLLAPS_MENU: 'COLLAPS_MENU',

    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE:'FETCH_DATA_FAILURE',

    FETCH_DETAIL_REQUEST: 'FETCH_DETAIL_REQUEST',
    FETCH_DETAIL_SUCCESS:'FETCH_DETAIL_SUCCESS',
    FETCH_DETAIL_FAILURE:'FETCH_DETAIL_FAILURE',
}

export default ActionTypes;
